---
title: IQB Testprofil International
lang: en
---

ID of profile-store: `ptesti`

Creator: IQB - Institut zur Qualitätsentwicklung im Bildungswesen

2 profiles defined:

# Testprofil - Aufgabe

ID of profile: `https://raw.githubusercontent.com/iqb-vocabs/p00/master/unit.json`

## Stimulus

| Name/Label | Type | Parameter | ID profile entry |
| :--- | :---: | :--- | :---: |
| Entwickler:in | Text | single line, Language(s): en   | iqb_author |
| Grundfärben | [vocabulary](https://w3id.org/iqb/v99/pc/) | url: 'https://w3id.org/iqb/v99/pc/', multiple selection, display: Dialog box | iqb_grundfarben |
| Stimuluszeit | Number | decimal places: 0, minimum value: 0, maximum value: none, as seconds | iqb_time_stimulus |

: {tbl-colwidths="[15,15,55,15]"}

## Quelle

| Name/Label | Type | Parameter | ID profile entry |
| :--- | :---: | :--- | :---: |
| Für SPF geeignet | Yes/No | text for TRUE': ja, text for FALSE: nein | iqb_spf |
| Notizfeld | Text | multiples lines, Language(s): en   | iqb_note_field |
| Sekundarfärben | [vocabulary](https://w3id.org/iqb/v99/sc/) | url: 'https://w3id.org/iqb/v99/sc/', multiple selection, display: Dialog box, numbering suppressed | iqb_sekundarfarben |

: {tbl-colwidths="[15,15,55,15]"}

# Testprofil International - Item

ID of profile: `https://raw.githubusercontent.com/iqb-vocabs/p00/master/item.json`

## Item

| Name/Label | Type | Parameter | ID profile entry |
| :--- | :---: | :--- | :---: |
| Boolean Item | Yes/No | text for TRUE': störend, text for FALSE: nicht relevant | b0 |
| Wortanzahl | Number | decimal places: 0, minimum value: 0, maximum value: none | iqb_word_count |

: {tbl-colwidths="[15,15,55,15]"}

## Bildungstandards

| Name/Label | Type | Parameter | ID profile entry |
| :--- | :---: | :--- | :---: |
| Funktionale ESA | [vocabulary](https://w3id.org/iqb/v56/fe/) | url: 'https://w3id.org/iqb/v56/fe/', multiple selection, display: Dialog box, numbering suppressed | s1 |
| Funktionale MSA | [vocabulary](https://w3id.org/iqb/v56/fm/) | url: 'https://w3id.org/iqb/v56/fm/', multiple selection, show only first level, display: Dialog box, numbering suppressed | s2 |
| Sprachbewusstheit ESA | [vocabulary](https://w3id.org/iqb/v56/be/) | url: 'https://w3id.org/iqb/v56/be/', multiple selection, display: Dialog box, numbering suppressed | s3 |
| Sprachbewusstheit MSA | [vocabulary](https://w3id.org/iqb/v56/bm/) | url: 'https://w3id.org/iqb/v56/bm/', multiple selection, display: Dialog box, numbering suppressed | s4 |
| Interkulturelle Kompetenz ESA | [vocabulary](https://w3id.org/iqb/v56/fe/) | url: 'https://w3id.org/iqb/v56/fe/', multiple selection, display: Dialog box, numbering suppressed | s5 |
| Interkulturelle Kompetenz MSA | [vocabulary](https://w3id.org/iqb/v56/im/) | url: 'https://w3id.org/iqb/v56/im/', multiple selection, display: Dialog box, numbering suppressed | s6 |
| Text- und Medienkompetenz ESA | [vocabulary](https://w3id.org/iqb/v56/te/) | url: 'https://w3id.org/iqb/v56/te/', multiple selection, display: Dialog box, numbering suppressed | s7 |
| Text- und Medienkompetenz MSA | [vocabulary](https://w3id.org/iqb/v56/tm/) | url: 'https://w3id.org/iqb/v56/tm/', multiple selection, display: Dialog box, numbering suppressed | s8 |

: {tbl-colwidths="[15,15,55,15]"}

