---
title: IQB Testprofil International
lang: en
---

ID of profile-store: `ptesti`

Creatur: IQB - Institut zur Qualitätsentwicklung im Bildungswesen

2 Profils definìs:

# Testprofil - Aufgabe

ID of profile: `https://raw.githubusercontent.com/iqb-vocabs/p00/master/unit.json`

## Stimulus

| Num/Label | tip | Parameter | ID profil register |
| :--- | :---: | :--- | :---: |
| Entwickler:in | text | Einzeilig, Lingua(s): rm   | iqb_author |
| Grundfärben | [vocabulari](https://w3id.org/iqb/v99/pc/) | url: 'https://w3id.org/iqb/v99/pc/', Elecziun multipla, preschentaziun: dialogbox | iqb_grundfarben |
| Stimuluszeit | nomer | Commastels: 0, valur minimala: 0, valur maximala: nagin, sco secondas | iqb_time_stimulus |

: {tbl-colwidths="[15,15,55,15]"}

## Quelle

| Num/Label | tip | Parameter | ID profil register |
| :--- | :---: | :--- | :---: |
| Für SPF geeignet | gea/na | Text per VAIR: ja, Text per FAUSS: nein | iqb_spf |
| Notizfeld | text | Mehrzeilig, Lingua(s): rm   | iqb_note_field |
| Sekundarfärben | [vocabulari](https://w3id.org/iqb/v99/sc/) | url: 'https://w3id.org/iqb/v99/sc/', Elecziun multipla, preschentaziun: dialogbox, numeraziun supprimida | iqb_sekundarfarben |

: {tbl-colwidths="[15,15,55,15]"}

# Testprofil International - Item

ID of profile: `https://raw.githubusercontent.com/iqb-vocabs/p00/master/item.json`

## Item

| Num/Label | tip | Parameter | ID profil register |
| :--- | :---: | :--- | :---: |
| Boolean Item | gea/na | Text per VAIR: störend, Text per FAUSS: nicht relevant | b0 |
| Wortanzahl | nomer | Commastels: 0, valur minimala: 0, valur maximala: nagin | iqb_word_count |

: {tbl-colwidths="[15,15,55,15]"}

## Bildungstandards

| Num/Label | tip | Parameter | ID profil register |
| :--- | :---: | :--- | :---: |
| Funktionale ESA | [vocabulari](https://w3id.org/iqb/v56/fe/) | url: 'https://w3id.org/iqb/v56/fe/', Elecziun multipla, preschentaziun: dialogbox, numeraziun supprimida | s1 |
| Funktionale MSA | [vocabulari](https://w3id.org/iqb/v56/fm/) | url: 'https://w3id.org/iqb/v56/fm/', Elecziun multipla, mussescha mo emprim nivel, preschentaziun: dialogbox, numeraziun supprimida | s2 |
| Sprachbewusstheit ESA | [vocabulari](https://w3id.org/iqb/v56/be/) | url: 'https://w3id.org/iqb/v56/be/', Elecziun multipla, preschentaziun: dialogbox, numeraziun supprimida | s3 |
| Sprachbewusstheit MSA | [vocabulari](https://w3id.org/iqb/v56/bm/) | url: 'https://w3id.org/iqb/v56/bm/', Elecziun multipla, preschentaziun: dialogbox, numeraziun supprimida | s4 |
| Interkulturelle Kompetenz ESA | [vocabulari](https://w3id.org/iqb/v56/fe/) | url: 'https://w3id.org/iqb/v56/fe/', Elecziun multipla, preschentaziun: dialogbox, numeraziun supprimida | s5 |
| Interkulturelle Kompetenz MSA | [vocabulari](https://w3id.org/iqb/v56/im/) | url: 'https://w3id.org/iqb/v56/im/', Elecziun multipla, preschentaziun: dialogbox, numeraziun supprimida | s6 |
| text- und Medienkompetenz ESA | [vocabulari](https://w3id.org/iqb/v56/te/) | url: 'https://w3id.org/iqb/v56/te/', Elecziun multipla, preschentaziun: dialogbox, numeraziun supprimida | s7 |
| text- und Medienkompetenz MSA | [vocabulari](https://w3id.org/iqb/v56/tm/) | url: 'https://w3id.org/iqb/v56/tm/', Elecziun multipla, preschentaziun: dialogbox, numeraziun supprimida | s8 |

: {tbl-colwidths="[15,15,55,15]"}

